
import java.awt.Color;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lea
 */
public class Sale_Window extends javax.swing.JFrame {

    /**
     * Creates new form Sale_Window
     */
    public Sale_Window() {
        initComponents();
        
        Border panel_border = BorderFactory.createMatteBorder(0,0,4,0, new Color(139, 0, 0));
        jPanel_Title1.setBorder(panel_border);
        
        fillJtableVehicles();
        
        fillJtableClients();
        
        fillJtableSales();
    }
    
    public void fillJtableVehicles(){
        
        V_VEHICLE vehicle = new V_VEHICLE();
        ArrayList<V_VEHICLE> vehicleList = vehicle.vehiclesList();
        
        String[] colNames = {"ID",  "Owner ID", "Price", "Brand", "Year"};
        
        Object[][] rows = new Object[vehicleList.size()][5];
        
        for(int i = 0; i < vehicleList.size(); i++){
            rows[i][0] = vehicleList.get(i).getId();
            rows[i][1] = vehicleList.get(i).getOwnerId();
            rows[i][2] = vehicleList.get(i).getPrice();
            rows[i][3] = vehicleList.get(i).getBrand();
            rows[i][4] = vehicleList.get(i).getYear();
        }
        
        DefaultTableModel model = (new DefaultTableModel(rows, colNames));
        jTable_Vehicles.setModel(model);
      
        jTable_Vehicles.setRowHeight(40);
        jTable_Vehicles.setSelectionBackground(new Color(0,153,76));
        jTable_Vehicles.getColumnModel().getColumn(0).setPreferredWidth(25);
        
        
    }

    public void fillJtableClients(){
        
        V_CLIENT vehicle = new V_CLIENT();
        ArrayList<V_CLIENT> vehicleList = vehicle.clientsList();
        
        String[] colNames = {"ID",  "First Name", "Last Name"};
        
        Object[][] rows = new Object[vehicleList.size()][3];
        
        for(int i = 0; i < vehicleList.size(); i++){
            rows[i][0] = vehicleList.get(i).getId();
            rows[i][1] = vehicleList.get(i).getFname();
            rows[i][2] = vehicleList.get(i).getLname();
            
        }
        
        DefaultTableModel model = (new DefaultTableModel(rows, colNames));
        jTable_Clients.setModel(model);
      
        jTable_Clients.setRowHeight(40);
        jTable_Clients.setSelectionBackground(new Color(0,153,76));
        jTable_Clients.getColumnModel().getColumn(0).setPreferredWidth(25);
        
        
    }
    
    public void fillJtableSales(){
        
        V_SALE sale = new V_SALE();
        ArrayList<V_SALE> salesList = sale.salesList();
        
        String[] colNames = {"ID",  "Vehicle", "Client", "Price", "Date"};
        
        Object[][] rows = new Object[salesList.size()][5];
        
        for(int i = 0; i < salesList.size(); i++){
            rows[i][0] = salesList.get(i).getId();
            rows[i][1] = salesList.get(i).getVehicleId();
            rows[i][2] = salesList.get(i).getClientId();
            rows[i][3] = salesList.get(i).getFinalPrice();
            rows[i][4] = salesList.get(i).getSellingDate();
            
        }
        
        DefaultTableModel model = (new DefaultTableModel(rows, colNames));
        jTable_Sales.setModel(model);
      
        jTable_Sales.setRowHeight(40);
        jTable_Sales.setSelectionBackground(new Color(0,153,76));
        jTable_Sales.getColumnModel().getColumn(0).setPreferredWidth(25);
        
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel_Title1 = new javax.swing.JPanel();
        jLabel_Title1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_Id = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField_VehicleId = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField_ClientId = new javax.swing.JTextField();
        jTextField_FinalPrice = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_Vehicles = new javax.swing.JTable();
        jButton_Remove_Sale = new javax.swing.JButton();
        jButton_Edit_Sale = new javax.swing.JButton();
        jButton_Add_Sale = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable_Clients = new javax.swing.JTable();
        jDateChooser_SaleDate = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable_Sales = new javax.swing.JTable();
        jButton_Refresh_Sale = new javax.swing.JButton();
        jButton_Add_Client = new javax.swing.JButton();
        jButton_Add_Vehicle = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 145, 145));

        jPanel_Title1.setBackground(new java.awt.Color(242, 62, 62));

        jLabel_Title1.setFont(new java.awt.Font("Tahoma", 1, 50)); // NOI18N
        jLabel_Title1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Title1.setText("Sale");

        javax.swing.GroupLayout jPanel_Title1Layout = new javax.swing.GroupLayout(jPanel_Title1);
        jPanel_Title1.setLayout(jPanel_Title1Layout);
        jPanel_Title1Layout.setHorizontalGroup(
            jPanel_Title1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_Title1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_Title1)
                .addGap(640, 640, 640))
        );
        jPanel_Title1Layout.setVerticalGroup(
            jPanel_Title1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Title1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel_Title1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jLabel2.setText("ID: ");

        jTextField_Id.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jLabel1.setText("Vehicle ID:");

        jTextField_VehicleId.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jLabel4.setText("Client ID:");

        jTextField_ClientId.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N

        jTextField_FinalPrice.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jLabel6.setText("Sale Date:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jLabel5.setText("Final Price:");

        jTable_Vehicles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable_Vehicles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_VehiclesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable_Vehicles);

        jButton_Remove_Sale.setBackground(new java.awt.Color(255, 51, 51));
        jButton_Remove_Sale.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jButton_Remove_Sale.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Remove_Sale.setText("Remove");
        jButton_Remove_Sale.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Remove_Sale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Remove_SaleActionPerformed(evt);
            }
        });

        jButton_Edit_Sale.setBackground(new java.awt.Color(255, 204, 0));
        jButton_Edit_Sale.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jButton_Edit_Sale.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Edit_Sale.setText("Edit");
        jButton_Edit_Sale.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Edit_Sale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Edit_SaleActionPerformed(evt);
            }
        });

        jButton_Add_Sale.setBackground(new java.awt.Color(0, 204, 0));
        jButton_Add_Sale.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jButton_Add_Sale.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Add_Sale.setText("Add");
        jButton_Add_Sale.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Add_Sale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Add_SaleActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Vehicles List ");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Clients List ");

        jTable_Clients.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable_Clients.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_ClientsMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable_Clients);

        jDateChooser_SaleDate.setDateFormatString("dd/MM/yyyy");
        jDateChooser_SaleDate.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Sales List");

        jTable_Sales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable_Sales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_SalesMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTable_Sales);

        jButton_Refresh_Sale.setBackground(new java.awt.Color(153, 153, 255));
        jButton_Refresh_Sale.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jButton_Refresh_Sale.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Refresh_Sale.setText("Refresh");
        jButton_Refresh_Sale.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Refresh_Sale.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_Refresh_SaleMouseClicked(evt);
            }
        });
        jButton_Refresh_Sale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Refresh_SaleActionPerformed(evt);
            }
        });

        jButton_Add_Client.setBackground(new java.awt.Color(0, 204, 204));
        jButton_Add_Client.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jButton_Add_Client.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Add_Client.setText("Add new Client");
        jButton_Add_Client.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Add_Client.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_Add_ClientMouseClicked(evt);
            }
        });
        jButton_Add_Client.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Add_ClientActionPerformed(evt);
            }
        });

        jButton_Add_Vehicle.setBackground(new java.awt.Color(0, 204, 204));
        jButton_Add_Vehicle.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jButton_Add_Vehicle.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Add_Vehicle.setText("Add new Vehicle");
        jButton_Add_Vehicle.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Add_Vehicle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_Add_VehicleMouseClicked(evt);
            }
        });
        jButton_Add_Vehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Add_VehicleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Title1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField_Id)
                            .addComponent(jTextField_VehicleId, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_ClientId, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateChooser_SaleDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                            .addComponent(jTextField_FinalPrice, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_Edit_Sale, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_Remove_Sale, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_Refresh_Sale, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_Add_Sale, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel9)))
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton_Add_Client, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel8))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Add_Vehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel_Title1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(jTextField_VehicleId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jTextField_ClientId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(jTextField_FinalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jDateChooser_SaleDate, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38)
                                .addComponent(jButton_Add_Sale, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_Edit_Sale, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton_Remove_Sale, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane4))
                        .addGap(18, 18, 18)
                        .addComponent(jButton_Refresh_Sale, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
                            .addComponent(jScrollPane2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_Add_Client)
                            .addComponent(jButton_Add_Vehicle))))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable_VehiclesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_VehiclesMouseClicked

        int selectedRowIndex = jTable_Vehicles.getSelectedRow();
        jTextField_VehicleId.setText(jTable_Vehicles.getValueAt(selectedRowIndex, 0).toString());
        
        jTextField_FinalPrice.setText(jTable_Vehicles.getValueAt(selectedRowIndex, 2).toString());
        
    }//GEN-LAST:event_jTable_VehiclesMouseClicked

    private void jButton_Remove_SaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Remove_SaleActionPerformed

       try{
            int id = Integer.valueOf(jTextField_Id.getText());
       
            if(new V_SALE().deleteSale(id)){
                JOptionPane.showMessageDialog(null, "Sale Data Has Been Deleted", "Delete Sale", 0);
            }else {
                JOptionPane.showMessageDialog(null, "Sale Data Has NOT Been Deleted", "Delete Sale", 0);
            }
       }catch (Exception ex){
           JOptionPane.showMessageDialog(null, "Select The Sale ID", "Delete Sale ERROR", 0);
       }
        
       
        
    }//GEN-LAST:event_jButton_Remove_SaleActionPerformed

    private void jButton_Edit_SaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Edit_SaleActionPerformed
        
       try{
            int id = Integer.valueOf(jTextField_Id.getText());
            int vehicleId = Integer.valueOf(jTextField_VehicleId.getText());
            int clientId = Integer.valueOf(jTextField_ClientId.getText());
            String finalPrice = jTextField_FinalPrice.getText();
            SimpleDateFormat dateFormat = new SimpleDateFormat ("yyyy-MM-dd");
            String sellingDate = dateFormat.format(jDateChooser_SaleDate.getDate());

            V_SALE sale = new V_SALE(id, vehicleId, clientId, finalPrice, sellingDate);

            if(new V_SALE().editSaleData(sale)){
                JOptionPane.showMessageDialog(null, "Sale Data Has Been Updated", "Edit Sale", 0);
            }else {
                JOptionPane.showMessageDialog(null, "Sale Data Has NOT Been Updated", "Edit Sale", 0);
            }
       }catch (Exception ex){
           JOptionPane.showMessageDialog(null, "Select The Sale ID", "Edit Sale ERROR", 0);
       }
        
       
        
    }//GEN-LAST:event_jButton_Edit_SaleActionPerformed

    private void jButton_Add_SaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Add_SaleActionPerformed

        try{
            int vehicleId = Integer.valueOf(jTextField_VehicleId.getText());
            int clientId = Integer.valueOf(jTextField_ClientId.getText());
            String finalPrice = jTextField_FinalPrice.getText();
            SimpleDateFormat dateFormat = new SimpleDateFormat ("yyyy-MM-dd");
            String sellingDate = dateFormat.format(jDateChooser_SaleDate.getDate());

            V_SALE sale = new V_SALE(0, vehicleId, clientId, finalPrice, sellingDate);

            if(new V_SALE().addNewSale(sale)){
                JOptionPane.showMessageDialog(null, "A New Sale Has Been Created and Added", "Add Sale", 0);
            }else {
                JOptionPane.showMessageDialog(null, "A New Sale Has NOT Been Created and Added", "Add Sale", 0);
            }
        }catch (Exception ex){
            JOptionPane.showMessageDialog(null, "Select The Vehicle ID and Client ID", "Add Sale ERROR", 0);
        }


       
       
    }//GEN-LAST:event_jButton_Add_SaleActionPerformed

    private void jTable_ClientsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_ClientsMouseClicked
        
        int selectedRowIndex = jTable_Clients.getSelectedRow();
        jTextField_ClientId.setText(jTable_Clients.getValueAt(selectedRowIndex, 0).toString());
        
    }//GEN-LAST:event_jTable_ClientsMouseClicked

    private void jTable_SalesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_SalesMouseClicked
        
        int selectedRowIndex = jTable_Sales.getSelectedRow();
        jTextField_Id.setText(jTable_Sales.getValueAt(selectedRowIndex, 0).toString());
        jTextField_VehicleId.setText(jTable_Sales.getValueAt(selectedRowIndex, 1).toString());
        jTextField_ClientId.setText(jTable_Sales.getValueAt(selectedRowIndex, 2).toString());
        jTextField_FinalPrice.setText(jTable_Sales.getValueAt(selectedRowIndex, 3).toString());
        
        Date saleDate;
        try {
            saleDate = new SimpleDateFormat("yyyy-MM-dd").parse(jTable_Sales.getValueAt(selectedRowIndex, 4).toString());
            jDateChooser_SaleDate.setDate(saleDate);
        } catch (ParseException ex) {
            Logger.getLogger(Sale_Window.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }//GEN-LAST:event_jTable_SalesMouseClicked

    private void jButton_Refresh_SaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Refresh_SaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_Refresh_SaleActionPerformed

    private void jButton_Refresh_SaleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_Refresh_SaleMouseClicked
        
        fillJtableVehicles();
        
        fillJtableClients();
        
        fillJtableSales();
        
    }//GEN-LAST:event_jButton_Refresh_SaleMouseClicked

    private void jButton_Add_ClientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_Add_ClientMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_Add_ClientMouseClicked

    private void jButton_Add_ClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Add_ClientActionPerformed
        Client_Window clientform = new Client_Window();
        clientform.setVisible(true);
        clientform.pack();
        clientform.setLocationRelativeTo(null);
        clientform.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jButton_Add_ClientActionPerformed

    private void jButton_Add_VehicleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_Add_VehicleMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_Add_VehicleMouseClicked

    private void jButton_Add_VehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Add_VehicleActionPerformed
        
        Vehicle_Window vehicleform = new Vehicle_Window();
        vehicleform.setVisible(true);
        vehicleform.pack();
        vehicleform.setLocationRelativeTo(null);
        vehicleform.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
    }//GEN-LAST:event_jButton_Add_VehicleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sale_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sale_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sale_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sale_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sale_Window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Add_Client;
    private javax.swing.JButton jButton_Add_Sale;
    private javax.swing.JButton jButton_Add_Vehicle;
    private javax.swing.JButton jButton_Edit_Sale;
    private javax.swing.JButton jButton_Refresh_Sale;
    private javax.swing.JButton jButton_Remove_Sale;
    private com.toedter.calendar.JDateChooser jDateChooser_SaleDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_Title1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_Title1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable_Clients;
    private javax.swing.JTable jTable_Sales;
    private javax.swing.JTable jTable_Vehicles;
    private javax.swing.JTextField jTextField_ClientId;
    private javax.swing.JTextField jTextField_FinalPrice;
    private javax.swing.JTextField jTextField_Id;
    private javax.swing.JTextField jTextField_VehicleId;
    // End of variables declaration//GEN-END:variables
}
