
import java.awt.Color;
import java.util.Calendar;
import java.util.HashMap;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lea
 */
public class Vehicle_Window extends javax.swing.JFrame {

    /**
     * Creates new form Vehicle_Window
     */
    
    V_TYPE type = new V_TYPE();
    HashMap<String, Integer> map = type.getTypesMap();
    
    
    public Vehicle_Window() {
        initComponents();
        
        Border panel_border = BorderFactory.createMatteBorder(0,0,4,0, new Color(91,121,91));
        jPanel_Title1.setBorder(panel_border);
        
        bindCombo();
    }
    
    //function to populate jcombobox with types data
    
    public void bindCombo(){
       
        for(String s : map.keySet()){
            jComboBox_Type.addItem(s);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel_Title1 = new javax.swing.JPanel();
        jLabel_Title1 = new javax.swing.JLabel();
        jTextField_Id = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField_Price = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField_OwnersId = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField_Kilometers = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton_Add_Vehicle = new javax.swing.JButton();
        jButton_Edit_Vehicle = new javax.swing.JButton();
        jButton_Remove_Vehicle = new javax.swing.JButton();
        jButton_Search_Vehicle = new javax.swing.JButton();
        jTextField_Brand = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField_Motor = new javax.swing.JTextField();
        jComboBox_Type = new javax.swing.JComboBox();
        jSpinner_Doors = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        jSpinner_Seats = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        jSpinner_Year = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jCheckBox_AC = new javax.swing.JCheckBox();
        jCheckBox_CAS = new javax.swing.JCheckBox();
        jCheckBox_PS = new javax.swing.JCheckBox();
        jCheckBox_GPS = new javax.swing.JCheckBox();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_Problems = new javax.swing.JTextArea();
        jButton_Show_Vehicle = new javax.swing.JButton();
        jComboBox_Color = new javax.swing.JComboBox();
        jComboBox_Gear = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 229, 204));

        jPanel_Title1.setBackground(new java.awt.Color(153, 203, 153));

        jLabel_Title1.setFont(new java.awt.Font("Tahoma", 1, 50)); // NOI18N
        jLabel_Title1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Title1.setText("Vehicles");

        javax.swing.GroupLayout jPanel_Title1Layout = new javax.swing.GroupLayout(jPanel_Title1);
        jPanel_Title1.setLayout(jPanel_Title1Layout);
        jPanel_Title1Layout.setHorizontalGroup(
            jPanel_Title1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_Title1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_Title1)
                .addGap(580, 580, 580))
        );
        jPanel_Title1Layout.setVerticalGroup(
            jPanel_Title1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Title1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel_Title1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTextField_Id.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jLabel2.setText("ID: ");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jLabel1.setText("Type:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jLabel4.setText("Price (€):");

        jTextField_Price.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jLabel5.setText("Owner ID:");

        jTextField_OwnersId.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jLabel6.setText("Kilometers:");

        jTextField_Kilometers.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jLabel3.setText("Brand:");

        jButton_Add_Vehicle.setBackground(new java.awt.Color(0, 204, 0));
        jButton_Add_Vehicle.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jButton_Add_Vehicle.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Add_Vehicle.setText("Add");
        jButton_Add_Vehicle.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Add_Vehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Add_VehicleActionPerformed(evt);
            }
        });

        jButton_Edit_Vehicle.setBackground(new java.awt.Color(255, 204, 0));
        jButton_Edit_Vehicle.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jButton_Edit_Vehicle.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Edit_Vehicle.setText("Edit");
        jButton_Edit_Vehicle.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Edit_Vehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Edit_VehicleActionPerformed(evt);
            }
        });

        jButton_Remove_Vehicle.setBackground(new java.awt.Color(255, 51, 51));
        jButton_Remove_Vehicle.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jButton_Remove_Vehicle.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Remove_Vehicle.setText("Remove");
        jButton_Remove_Vehicle.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Remove_Vehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Remove_VehicleActionPerformed(evt);
            }
        });

        jButton_Search_Vehicle.setBackground(new java.awt.Color(0, 102, 0));
        jButton_Search_Vehicle.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jButton_Search_Vehicle.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Search_Vehicle.setText("Search");
        jButton_Search_Vehicle.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Search_Vehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Search_VehicleActionPerformed(evt);
            }
        });

        jTextField_Brand.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jLabel7.setText("Motor:");

        jTextField_Motor.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N

        jComboBox_Type.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N

        jSpinner_Doors.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N
        jSpinner_Doors.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jLabel9.setText("Seats:");

        jSpinner_Seats.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N
        jSpinner_Seats.setModel(new javax.swing.SpinnerNumberModel(0, 0, 20, 1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jLabel10.setText("Year:");

        jSpinner_Year.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N
        jSpinner_Year.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(2000), Integer.valueOf(1960), null, Integer.valueOf(1)));
        jSpinner_Year.setValue(1960);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jLabel11.setText("Gear:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jLabel12.setText("Color:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jLabel13.setText("Doors:");

        jCheckBox_AC.setFont(new java.awt.Font("Tahoma", 0, 29)); // NOI18N
        jCheckBox_AC.setText("Air conditioner");
        jCheckBox_AC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_ACActionPerformed(evt);
            }
        });

        jCheckBox_CAS.setFont(new java.awt.Font("Tahoma", 0, 29)); // NOI18N
        jCheckBox_CAS.setText("Car audio system");

        jCheckBox_PS.setFont(new java.awt.Font("Tahoma", 0, 29)); // NOI18N
        jCheckBox_PS.setText("Parking sensors");

        jCheckBox_GPS.setFont(new java.awt.Font("Tahoma", 0, 29)); // NOI18N
        jCheckBox_GPS.setText("GPS");
        jCheckBox_GPS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_GPSActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jLabel14.setText("Problems:");

        jTextArea_Problems.setColumns(20);
        jTextArea_Problems.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N
        jTextArea_Problems.setRows(5);
        jScrollPane1.setViewportView(jTextArea_Problems);

        jButton_Show_Vehicle.setBackground(new java.awt.Color(102, 102, 255));
        jButton_Show_Vehicle.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jButton_Show_Vehicle.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Show_Vehicle.setText("Show vehicle");
        jButton_Show_Vehicle.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Show_Vehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Show_VehicleActionPerformed(evt);
            }
        });

        jComboBox_Color.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N
        jComboBox_Color.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Blue", "Black", "Coral", "Dark blue", "Dark green", "Green", "Grey", "Mouse Grey", "Orange", "Red", "Pink", "White" }));

        jComboBox_Gear.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N
        jComboBox_Gear.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mehanical", "Automatic", "Semi-automatic" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Title1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton_Add_Vehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(jButton_Edit_Vehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(jButton_Remove_Vehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(434, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_Price)
                            .addComponent(jTextField_OwnersId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                            .addComponent(jTextField_Kilometers, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField_Id, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_Search_Vehicle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jTextField_Brand, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                            .addComponent(jComboBox_Type, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField_Motor))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(123, 123, 123)
                                    .addComponent(jLabel10))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel13)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jButton_Show_Vehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jComboBox_Gear, 0, 248, Short.MAX_VALUE)
                                            .addComponent(jSpinner_Seats, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jSpinner_Doors, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jSpinner_Year, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jComboBox_Color, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jCheckBox_AC)
                                            .addComponent(jCheckBox_CAS)
                                            .addComponent(jCheckBox_PS)
                                            .addComponent(jCheckBox_GPS))))
                                .addGap(56, 56, 56))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel_Title1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton_Search_Vehicle)
                                .addComponent(jSpinner_Doors, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2)
                            .addComponent(jTextField_Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jComboBox_Type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jSpinner_Seats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField_Price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextField_OwnersId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextField_Kilometers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(jComboBox_Gear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(101, 101, 101)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jSpinner_Year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jComboBox_Color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jCheckBox_AC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox_CAS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox_PS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox_GPS)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField_Brand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_Motor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Add_Vehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Edit_Vehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Remove_Vehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Show_Vehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_Add_VehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Add_VehicleActionPerformed

        
       try{
            int current_year = Calendar.getInstance().get(Calendar.YEAR);
            
            int type = map.get(jComboBox_Type.getSelectedItem().toString());
            int ownerId = Integer.valueOf(jTextField_OwnersId.getText());
            int doors = Integer.valueOf(jSpinner_Doors.getValue().toString());
            int seats = Integer.valueOf(jSpinner_Seats.getValue().toString());
            int year = Integer.valueOf(jSpinner_Year.getValue().toString());
            
            
            
            boolean have_ac = false;
            boolean have_gps = false;
            boolean have_ps = false;
            boolean have_cas = false;
            
            //check if vehicle have ac, gps, ps or/and cas
            if(jCheckBox_AC.isSelected() )have_ac = true;
            if(jCheckBox_GPS.isSelected() )have_gps = true;
            if(jCheckBox_PS.isSelected() )have_ps = true;
            if(jCheckBox_CAS.isSelected() )have_cas = true;
            
            
            String price = String.valueOf(jTextField_Price.getText());
            String kilometers = String.valueOf(jTextField_Kilometers.getText());
            String brand = String.valueOf(jTextField_Brand.getText());
            String motor = String.valueOf(jTextField_Motor.getText());
            String problems = String.valueOf(jTextArea_Problems.getText());
            String color = String.valueOf(jComboBox_Color.getSelectedItem());
            String gear = String.valueOf(jComboBox_Gear.getSelectedItem());
            
            V_VEHICLE vehicle = new V_VEHICLE(0, type, ownerId, price, kilometers, brand, motor, color, gear, doors, seats, year, have_ac, have_ps, have_cas, have_gps, problems);
            
            if(new V_VEHICLE().addNewVehicle(vehicle)&& year< current_year){
                
                JOptionPane.showMessageDialog(null, "New vehicle added to the system", "Add vehicle", 1);
                
                jTextField_Id.setText("");
                        jTextField_Price.setText("");
                        jTextField_OwnersId.setText("");
                        jTextField_Kilometers.setText("");
                        jTextField_Brand.setText("");
                        jTextField_Motor.setText("");
                        
                        jComboBox_Color.setSelectedIndex(0);
                        jComboBox_Gear.setSelectedIndex(0);
                        jSpinner_Doors.setValue(0);
                        jSpinner_Seats.setValue(0);
                        jSpinner_Year.setValue(0);
                        
                        jCheckBox_AC.setSelected(false);
                        jCheckBox_GPS.setSelected(false);
                        jCheckBox_CAS.setSelected(false);
                        jCheckBox_PS.setSelected(false);
                        
                        jTextArea_Problems.setText("");
                
            }
            else{
                JOptionPane.showMessageDialog(null, "Vehicle NOT added to the system", "Add vehicle", 2);
            }
            
       }
       catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex.getMessage() + " ERROR", "ERROR", 0);
        }
       
       
        
    }//GEN-LAST:event_jButton_Add_VehicleActionPerformed

    private void jButton_Edit_VehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Edit_VehicleActionPerformed

         try{
            int id = Integer.valueOf(jTextField_Id.getText());
            int type = map.get(jComboBox_Type.getSelectedItem().toString());
            int ownerId = Integer.valueOf(jTextField_OwnersId.getText());
            int doors = Integer.valueOf(jSpinner_Doors.getValue().toString());
            int seats = Integer.valueOf(jSpinner_Seats.getValue().toString());
            int year = Integer.valueOf(jSpinner_Year.getValue().toString());
            
            boolean have_ac = false;
            boolean have_gps = false;
            boolean have_ps = false;
            boolean have_cas = false;
            
            //check if vehicle have ac, gps, ps or/and cas
            if(jCheckBox_AC.isSelected() )have_ac = true;
            if(jCheckBox_GPS.isSelected() )have_gps = true;
            if(jCheckBox_PS.isSelected() )have_ps = true;
            if(jCheckBox_CAS.isSelected() )have_cas = true;
            
            
            String price = String.valueOf(jTextField_Price.getText());
            String kilometers = String.valueOf(jTextField_Kilometers.getText());
            String brand = String.valueOf(jTextField_Brand.getText());
            String motor = String.valueOf(jTextField_Motor.getText());
            String problems = String.valueOf(jTextArea_Problems.getText());
            String color = String.valueOf(jComboBox_Color.getSelectedItem());
            String gear = String.valueOf(jComboBox_Gear.getSelectedItem());
            
            V_VEHICLE vehicle = new V_VEHICLE(id, type, ownerId, price, kilometers, brand, motor, color, gear, doors, seats, year, have_ac, have_ps, have_cas, have_gps, problems);
            
            if(new V_VEHICLE().editVehicle(vehicle)){
                JOptionPane.showMessageDialog(null, "Vehicle updated", "Edit vehicle", 1);
                
                jTextField_Id.setText("");
                        jTextField_Price.setText("");
                        jTextField_OwnersId.setText("");
                        jTextField_Kilometers.setText("");
                        jTextField_Brand.setText("");
                        jTextField_Motor.setText("");
                        
                        jComboBox_Color.setSelectedIndex(0);
                        jComboBox_Gear.setSelectedIndex(0);
                        jSpinner_Doors.setValue(0);
                        jSpinner_Seats.setValue(0);
                        jSpinner_Year.setValue(0);
                        
                        jCheckBox_AC.setSelected(false);
                        jCheckBox_GPS.setSelected(false);
                        jCheckBox_CAS.setSelected(false);
                        jCheckBox_PS.setSelected(false);
                        
                        jTextArea_Problems.setText("");
            }
            else{
                JOptionPane.showMessageDialog(null, "Vehicle NOT updated", "Edit vehicle", 2);
            }
            
       }
       catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex.getMessage() + " Please enter valid vehicle ID and owner ID", "Invalid Data", 0);
        }
        
    }//GEN-LAST:event_jButton_Edit_VehicleActionPerformed

    private void jButton_Remove_VehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Remove_VehicleActionPerformed

        try{
            int vehicletId = Integer.valueOf(jTextField_Id.getText());

            V_VEHICLE vehicle = new V_VEHICLE();

            if(jTextField_Id.getText().trim().equals("")){
                JOptionPane.showMessageDialog(null, "Please enter the Vehicle ID", "Empty ID field", 2);
            }
            else{

                int yes_or_no = JOptionPane.showConfirmDialog(null, "Do you want to delete this vehicle?", "Delete Client", JOptionPane.YES_NO_OPTION );

                if(yes_or_no == JOptionPane.YES_OPTION){

                    if(vehicle.removeVehicle(vehicletId)){
                        JOptionPane.showMessageDialog(null, "Vehicle deleted", "Delete Vehicle", 1);
                        
                        //clear all fields after deleting
                        jTextField_Id.setText("");
                        jTextField_Price.setText("");
                        jTextField_OwnersId.setText("");
                        jTextField_Kilometers.setText("");
                        jTextField_Brand.setText("");
                        jTextField_Motor.setText("");
                        
                        jComboBox_Color.setSelectedIndex(0);
                        jComboBox_Gear.setSelectedIndex(0);
                        jSpinner_Doors.setValue(0);
                        jSpinner_Seats.setValue(0);
                        jSpinner_Year.setValue(0);
                        
                        jCheckBox_AC.setSelected(false);
                        jCheckBox_GPS.setSelected(false);
                        jCheckBox_CAS.setSelected(false);
                        jCheckBox_PS.setSelected(false);
                        
                        jTextArea_Problems.setText("");
                        
                        
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "Operation failed", "Delete Vehicle", 2);
                    }

                }
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex.getMessage() + " Enter a valid ID", "Invalid ID", 0);
        }
    }//GEN-LAST:event_jButton_Remove_VehicleActionPerformed

    private void jCheckBox_ACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_ACActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_ACActionPerformed

    private void jCheckBox_GPSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_GPSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_GPSActionPerformed

    private void jButton_Show_VehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Show_VehicleActionPerformed
        
        //show all vehicles
        Show_Vehicles_Window vehicleform = new Show_Vehicles_Window();
        vehicleform.setVisible(true);
        vehicleform.pack();
        vehicleform.setLocationRelativeTo(null);
        vehicleform.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
    }//GEN-LAST:event_jButton_Show_VehicleActionPerformed

    private void jButton_Search_VehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Search_VehicleActionPerformed
        
        try{
            int vehicleId = Integer.valueOf(jTextField_Id.getText());
            V_VEHICLE vehicle = new V_VEHICLE().findVehicle(vehicleId);
            
            if(vehicle != null){
                jTextField_Price.setText(vehicle.getPrice());
                jTextField_OwnersId.setText(String.valueOf(vehicle.getOwnerId()));
                jTextField_Kilometers.setText(vehicle.getKilometers());
                jTextField_Brand.setText(vehicle.getBrand());
                jTextField_Motor.setText(vehicle.getMotor());
                
                for(Object type : map.keySet()){
                    if(map.get(type).equals(vehicle.getType())){
                        jComboBox_Type.setSelectedItem(type);
                    }
                }
                
                jComboBox_Color.setSelectedItem(map.get(vehicle.getColor()));
                jComboBox_Gear.setSelectedItem(map.get(vehicle.getGear()));
                jSpinner_Doors.setValue(vehicle.getDoors());
                jSpinner_Seats.setValue(vehicle.getSeats());
                jSpinner_Year.setValue(vehicle.getYear());
                jTextArea_Problems.setText(vehicle.getProblems());
                
                if(vehicle.isAc()) jCheckBox_AC.setSelected(true);
                if(vehicle.isGps()) jCheckBox_GPS.setSelected(true);
                if(vehicle.isCas()) jCheckBox_CAS.setSelected(true);
                if(vehicle.isPs()) jCheckBox_PS.setSelected(true);
                
            }
            else{
                JOptionPane.showMessageDialog(null, "Vehicle Not Found", "ERROR", 0);
            }
            
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex.getMessage() + " ERROR", "ERROR", 0);
        }
        
    }//GEN-LAST:event_jButton_Search_VehicleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vehicle_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vehicle_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vehicle_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vehicle_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vehicle_Window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Add_Vehicle;
    private javax.swing.JButton jButton_Edit_Vehicle;
    private javax.swing.JButton jButton_Remove_Vehicle;
    private javax.swing.JButton jButton_Search_Vehicle;
    private javax.swing.JButton jButton_Show_Vehicle;
    private javax.swing.JCheckBox jCheckBox_AC;
    private javax.swing.JCheckBox jCheckBox_CAS;
    private javax.swing.JCheckBox jCheckBox_GPS;
    private javax.swing.JCheckBox jCheckBox_PS;
    private javax.swing.JComboBox jComboBox_Color;
    private javax.swing.JComboBox jComboBox_Gear;
    private javax.swing.JComboBox jComboBox_Type;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_Title1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_Title1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner_Doors;
    private javax.swing.JSpinner jSpinner_Seats;
    private javax.swing.JSpinner jSpinner_Year;
    private javax.swing.JTextArea jTextArea_Problems;
    private javax.swing.JTextField jTextField_Brand;
    private javax.swing.JTextField jTextField_Id;
    private javax.swing.JTextField jTextField_Kilometers;
    private javax.swing.JTextField jTextField_Motor;
    private javax.swing.JTextField jTextField_OwnersId;
    private javax.swing.JTextField jTextField_Price;
    // End of variables declaration//GEN-END:variables
}
